In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 读入数据

In [3]:
f = open('iris.txt')
data = []
y=[]
for i in f.read().split():
    data.append([float(j)for j in i.split(',')[:-1]])
    y.append(i.split(',')[-1])
    
data = np.array(data) # 原始数据
n = data.shape[0] # 样本个数
m = data.shape[1] # 样本维数

# 计算核矩阵

In [4]:
def k(x1,x2):
    return x1.dot(x2)**2
km=np.zeros([n,n])
for i in range(n):
    for j in range(n):
        km[i][j]=k(data[i],data[j])
km

array([[ 4057.69  ,  5305.6656,  4748.5881, ...,  5449.3924,  7791.5929,
         2198.6721],
       [ 5305.6656,  6968.9104,  6244.1604, ...,  7133.4916, 10209.0816,
         2849.4244],
       [ 4748.5881,  6244.1604,  5598.0324, ...,  6372.8289,  9124.0704,
         2568.4624],
       ...,
       [ 5449.3924,  7133.4916,  6372.8289, ...,  7433.8884, 10586.3521,
         2769.9169],
       [ 7791.5929, 10209.0816,  9124.0704, ..., 10586.3521, 15242.3716,
         3928.7824],
       [ 2198.6721,  2849.4244,  2568.4624, ...,  2769.9169,  3928.7824,
         1588.8196]])

# 中心化

In [13]:
s=np.zeros([1,n])
for i in range(n):
    s=s+km[i]
mean = s/n
kms=np.zeros([n,n])
for i in range(n):
    kms[i]=km[i]-mean
kms

array([[  150.77790333,   192.98698533,   168.992446  , ...,
          222.44212733,   314.93935667,    33.67182867],
       [ 1398.75350333,  1856.23178533,  1664.564746  , ...,
         1906.54132733,  2732.42805667,   684.42412867],
       [  841.67600333,  1131.48178533,  1018.436746  , ...,
         1145.87862733,  1647.41685667,   403.46212867],
       ...,
       [ 1542.48030333,  2020.81298533,  1793.233246  , ...,
         2206.93812733,  3109.69855667,   604.91662867],
       [ 3884.68080333,  5096.40298533,  4544.474746  , ...,
         5359.40182733,  7765.71805667,  1763.78212867],
       [-1708.23999667, -2263.25421467, -2011.133254  , ...,
        -2457.03337267, -3547.87114333,  -576.18067133]])

# 标准化

In [14]:
kmn=np.zeros([n,n])
for j in range(n):
    biggest=kms[0][j]
    little=kms[0][j]
    for i in range(n):
        if kms[i][j]>biggest:
            biggest=kms[i][j]
        if kms[i][j]<little:
            little=kms[i][j]
    for i in range(n):     
        kmn[i][j]=(kms[i][j]-little)/(biggest-little)   
kmn

array([[0.40349685, 0.40405313, 0.40366731, ..., 0.40759841, 0.40526808,
        0.38485212],
       [0.60286502, 0.60619905, 0.60749824, ..., 0.60181116, 0.59823552,
        0.60763806],
       [0.51387007, 0.51811505, 0.51943772, ..., 0.51409044, 0.51162836,
        0.51145033],
       ...,
       [0.62582584, 0.62620177, 0.62503442, ..., 0.63645335, 0.62834979,
        0.58041856],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.97715774],
       [0.10651269, 0.10552874, 0.10653887, ..., 0.09859744, 0.09693296,
        0.17606829]])

# 使用核函数将每个点x变换到特征空间φ（x）

In [9]:
s1 = np.zeros([n,10])
a = 2.0**0.5
for i in range(n):
    s1[i] = np.array([data[i][0]**2,data[i][1]**2,data[i][2]**2,data[i][3]**2,
                       a*data[i][0]*data[i][1],a*data[i][1]*data[i][2],a*data[i][2]*data[i][3],
                       a*data[i][0]*data[i][2],a*data[i][1]*data[i][3],a*data[i][0]*data[i][3]])
s1

array([[34.81      ,  9.        , 17.64      , ..., 35.04421208,
         6.36396103, 12.51579003],
       [47.61      ,  9.61      , 24.01      , ..., 47.81456054,
         6.57609307, 14.63711037],
       [43.56      ,  8.41      , 21.16      , ..., 42.93552375,
         5.33158513, 12.13395237],
       ...,
       [44.89      ,  9.        , 27.04      , ..., 49.27120051,
         9.75807358, 21.793031  ],
       [59.29      , 14.44      , 44.89      , ..., 72.95927768,
        11.82282538, 23.95677775],
       [26.01      , 11.56      ,  2.25      , ..., 10.81873375,
         0.96166522,  1.44249783]])

In [11]:
def k(x1,x2):
    return x1.dot(x2)
km1=np.zeros([n,n])
for i in range(n):
    for j in range(n):
        km1[i][j]=k(s1[i],s1[j])
km1

array([[ 4057.69  ,  5305.6656,  4748.5881, ...,  5449.3924,  7791.5929,
         2198.6721],
       [ 5305.6656,  6968.9104,  6244.1604, ...,  7133.4916, 10209.0816,
         2849.4244],
       [ 4748.5881,  6244.1604,  5598.0324, ...,  6372.8289,  9124.0704,
         2568.4624],
       ...,
       [ 5449.3924,  7133.4916,  6372.8289, ...,  7433.8884, 10586.3521,
         2769.9169],
       [ 7791.5929, 10209.0816,  9124.0704, ..., 10586.3521, 15242.3716,
         3928.7824],
       [ 2198.6721,  2849.4244,  2568.4624, ...,  2769.9169,  3928.7824,
         1588.8196]])

# 居中这些点并对它们进行标准化

In [12]:
sum=np.zeros([1,n])
for i in range(n):
    sum=sum+km[i]
mean1 = sum/n
kms1=np.zeros([n,n])
for i in range(n):
    kms1[i]=km1[i]-mean1
kmn1=np.zeros([n,n])
for j in range(n):
    biggest=kms1[0][j]
    little=kms1[0][j]
    for i in range(n):
        if kms1[i][j]>biggest:
            biggest=kms1[i][j]
        if kms1[i][j]<little:
            little=kms1[i][j]
    for i in range(n):     
        kmn1[i][j]=(kms1[i][j]-little)/(biggest-little)   
kmn1

array([[0.40349685, 0.40405313, 0.40366731, ..., 0.40759841, 0.40526808,
        0.38485212],
       [0.60286502, 0.60619905, 0.60749824, ..., 0.60181116, 0.59823552,
        0.60763806],
       [0.51387007, 0.51811505, 0.51943772, ..., 0.51409044, 0.51162836,
        0.51145033],
       ...,
       [0.62582584, 0.62620177, 0.62503442, ..., 0.63645335, 0.62834979,
        0.58041856],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.97715774],
       [0.10651269, 0.10552874, 0.10653887, ..., 0.09859744, 0.09693296,
        0.17606829]])

# 对比发现，以上两种方案计算出的核矩阵相同